import { useEffect, useMemo, useState } from 'react'
import heroImg from './assets/hero.png'
import './App.css'

const projects = [
  { id: '01', title: 'FlowGuard', kind: 'Distributed API Gateway', stack: ['Go', 'Gin', 'Redis', 'PostgreSQL', 'GraphQL', 'Docker'], summary: 'A Go-based gateway for request routing, authentication, validation, rate limiting, and controlled service communication.', features: ['Distributed token-bucket rate limiting', 'JWT authentication and request tracing', 'Caching, indexing, health checks, and structured errors'], problem: 'Backend services need a reliable traffic boundary when requests arrive concurrently.', solution: 'Designed a reusable gateway layer that centralizes routing, auth, validation, and per-user/per-endpoint limits.', result: 'A maintainable foundation for distributed services with performance-minded request processing.' },
  { id: '02', title: 'GoPulse', kind: 'API Observability Platform', url: 'https://gopulse-api.onrender.com', stack: ['Go', 'Gin', 'PostgreSQL', 'Redis', 'GraphQL', 'Docker'], summary: 'A backend platform for monitoring API health, latency, throughput, error rates, and endpoint performance.', features: ['Request tracing and structured logging', 'GraphQL analytics across service metrics', 'PostgreSQL indexing and Redis caching'], problem: 'Service teams need clear signals before performance issues become outages.', solution: 'Built an observability layer that turns API activity into searchable metrics and operational feedback.', result: 'A focused platform for understanding reliability, performance, and usage patterns.' },
  { id: '03', title: 'InterviewMind', kind: 'Adaptive AI Interview Platform', stack: ['Python', 'FastAPI', 'LLM APIs', 'Embeddings', 'React'], summary: 'An adaptive AI interviewer that evaluates responses, identifies skill gaps, and selects follow-up questions.', features: ['Structured prompt engineering', 'Semantic similarity and embeddings', 'Personalized feedback and performance reports'], problem: 'Static interview flows cannot adapt to what a candidate actually understands.', solution: 'Combined LLM APIs, semantic relevance, and performance signals to make each interview responsive.', result: 'A practical AI application for technical assessment and skill estimation.' },
  { id: '04', title: 'KrishiLens', kind: 'AI-Powered Smart Farming', url: 'https://krishi-lens.vercel.app/', stack: ['React Native', 'CNN', 'Firebase', 'Firestore'], summary: 'A cross-platform farming application supporting crop disease detection, multilingual accessibility, and scan synchronization.', features: ['CNN-based crop image analysis', 'Firebase Authentication and Firestore', 'Farmer-focused learning resources and scan tracking'], problem: 'Farmers need accessible, practical support when identifying crop disease.', solution: 'Connected mobile workflows, image analysis, and cloud data to turn scans into useful guidance.', result: 'An AI-driven smart farming prototype developed during PU Code Hackathon 2.0.' },
  { id: '05', title: 'ChitChat', kind: 'Real-Time Messaging Platform', stack: ['React', 'Node.js', 'Express.js', 'MongoDB', 'Socket.IO', 'JWT'], summary: 'A real-time messaging platform for one-to-one and group communication, presence, and activity tracking.', features: ['Event-driven messaging and synchronization', 'JWT authentication and online presence', 'MongoDB schemas for conversations and messages'], problem: 'People expect conversations and presence to update instantly across devices.', solution: 'Built REST APIs and Socket.IO events around secure connection and message workflows.', result: 'A responsive communication system with low-latency real-time interaction.' },
  { id: '06', title: 'Real-Time Collaboration Workspace', kind: 'Distributed Collaboration Tool', stack: ['React.js', 'Node.js', 'MongoDB', 'Socket.IO'], summary: 'A collaborative workspace enabling concurrent document editing and synchronized updates.', features: ['Shared workspaces and live editing', 'Presence detection and conflict handling', 'REST APIs and Mongoose data models'], problem: 'Multiple users need to change shared state without losing consistency.', solution: 'Designed real-time channels and version-aware data flows for concurrent collaboration.', result: 'A practical distributed workspace experience across multiple users.' },
  { id: '07', title: 'Productivity Tracker', kind: 'Chrome Extension + Analytics', stack: ['JavaScript', 'Express.js', 'MongoDB', 'Chrome API'], summary: 'A browser productivity extension for distraction filtering, browsing activity, and focus sessions.', features: ['Activity monitoring and distraction filtering', 'Real-time productivity statistics', 'Browser storage and cloud synchronization'], problem: 'Focus is easier to protect when behavior is visible and actionable.', solution: 'Connected extension APIs with MERN analytics services and persistent user data.', result: 'A user-centric productivity system for tracking focus and browsing patterns.' },
  { id: '08', title: 'CortexOps', kind: 'Incident Management Platform', url: 'https://cortexops-b4c1.onrender.com/', stack: ['React', 'Vite', 'Operations Dashboard', 'Incident Tracking'], summary: 'An operations command center for reporting, triaging, monitoring, and resolving incidents in one focused workflow.', features: ['Incident reporting with severity tracking', 'Operational overview across open, active, and resolved events', 'Recent activity feed for team visibility'], problem: 'Operations teams need a shared view of risk from the first report through resolution.', solution: 'Built a focused incident management workspace that keeps event status, severity, and activity visible.', result: 'A practical control center for maintaining operational awareness and moving incidents toward closure.' },
  { id: '09', title: 'WeatherNow', kind: 'Real-Time Weather Application', url: 'https://weathernow-app-ri78.onrender.com', stack: ['React', 'Weather API', 'Responsive UI'], summary: 'A weather application for checking current conditions and forecasts through a focused, responsive interface.', features: ['Live weather lookup', 'Location-based conditions', 'Responsive forecast presentation'], problem: 'People need quick, readable weather information wherever they are.', solution: 'Built a lightweight weather experience around live forecast data and clear status presentation.', result: 'A practical weather utility accessible across desktop and mobile devices.' },
]

const techGroups = [
  ['LANGUAGES', 'Go', 'Java', 'JavaScript', 'TypeScript', 'Python', 'C', 'C++'],
  ['FRONTEND', 'React.js', 'React Native', 'Angular', 'Redux', 'HTML', 'CSS'],
  ['BACKEND', 'Gin', 'Node.js', 'Express.js', 'REST APIs', 'GraphQL', 'JWT', 'Socket.IO', 'WebSockets'],
  ['DATABASE', 'PostgreSQL', 'Redis', 'MongoDB', 'MySQL', 'Firebase', 'Firestore'],
  ['AI / ML', 'AI/ML', 'LLM APIs', 'Prompt Engineering', 'Embeddings', 'CNN', 'Image Analysis'],
  ['ENGINEERING', 'System Design', 'Distributed Systems', 'OOP', 'SOLID', 'LLD', 'Concurrency', 'Observability', 'Debugging'],
]

function App() {
  const [booted, setBooted] = useState(false)
  const [bootLine, setBootLine] = useState(0)
  const [selected, setSelected] = useState(null)
  const [terminalInput, setTerminalInput] = useState('')
  const [terminalLines, setTerminalLines] = useState(['> system online', '> Welcome to Kuldeep\'s engineering lab.'])
  const [active, setActive] = useState('home')
  const [cursor, setCursor] = useState({ x: -100, y: -100 })
  const [roles, setRoles] = useState(0)
  const [hoveredTech, setHoveredTech] = useState(null)
  const rolesList = useMemo(() => ['FULL STACK DEVELOPER', 'BACKEND ENGINEER', 'AI ENTHUSIAST', 'SYSTEM BUILDER', 'PROBLEM SOLVER'], [])

  useEffect(() => { const timer = setInterval(() => setBootLine((line) => { if (line >= 2) { clearInterval(timer); setTimeout(() => setBooted(true), 400); return line }; return line + 1 }), 650); return () => clearInterval(timer) }, [])
  useEffect(() => { const timer = setInterval(() => setRoles((role) => (role + 1) % rolesList.length), 6200); return () => clearInterval(timer) }, [rolesList.length])
  useEffect(() => { const move = (event) => setCursor({ x: event.clientX, y: event.clientY }); window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move) }, [])
  useEffect(() => { const onScroll = () => { const ids = ['home', 'about', 'experience', 'projects', 'systems', 'skills', 'achievements', 'contact']; const current = ids.find((id) => { const el = document.getElementById(id); return el && el.getBoundingClientRect().top > -160 && el.getBoundingClientRect().top < window.innerHeight * .55 }) || 'home'; setActive(current) }; window.addEventListener('scroll', onScroll); onScroll(); return () => window.removeEventListener('scroll', onScroll) }, [])

  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
  const runCommand = (event) => { event.preventDefault(); const command = terminalInput.trim().toLowerCase(); const responses = { help: 'commands: about / skills / projects / experience / achievements', about: 'Kuldeep Patil — Software Engineer, Full Stack Developer, Backend Engineer, AI Enthusiast.', skills: 'Go · Java · JavaScript · TypeScript · Python · React · Node.js · MongoDB · Firebase · APIs', projects: 'FlowGuard · GoPulse · InterviewMind · KrishiLens · ChitChat · Collaboration Workspace · Productivity Tracker · CortexOps', experience: 'Full Stack Developer Intern @ CODTECH IT Solutions Pvt. Ltd. · Aug 2025 — Oct 2025', achievements: '680+ DSA problems · LeetCode 1744 · CodeChef 1467 · ServiceNow CSA + CAD' }; setTerminalLines((lines) => [...lines, `> ${command}`, responses[command] || 'command not found — type help']); setTerminalInput('') }
  if (!booted) return <div className="boot"><div className="boot-mark">KP<span>◆</span></div><div className="boot-copy"><p>INITIALIZING KULDEEP.PATIL</p><p className={bootLine > 0 ? 'show' : ''}>LOADING DIGITAL EXPERIENCE...</p><p className={bootLine > 1 ? 'show online' : ''}>SYSTEM ONLINE</p></div><div className="boot-bar"><span style={{ width: `${(bootLine + 1) * 33.333}%` }} /></div><small>SECURE CONNECTION / 2026</small></div>

  return <><div className="cursor" style={{ transform: `translate(${cursor.x}px, ${cursor.y}px)` }} /><div className="ambient ambient-a" /><div className="ambient ambient-b" /><nav className={`nav shell ${active !== 'home' ? 'scrolled' : ''}`}><a className="brand" href="#home">KP<span>◆</span></a><div className="nav-links">{[['home','HOME'],['about','ABOUT'],['experience','EXPERIENCE'],['projects','PROJECTS'],['systems','SYSTEMS'],['skills','SKILLS'],['achievements','ACHIEVEMENTS'],['contact','CONTACT']].map(([id, label]) => <button className={active === id ? 'active' : ''} onClick={() => scrollTo(id)} key={id}>{label}</button>)}</div><a className="nav-signal" href="mailto:kp494563@gmail.com"><i /> ONLINE</a></nav>
  <main>
  <section className="hero shell" id="home"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span>SYS / 001</span> DIGITAL CREATOR / DEVELOPER</p><h1>KULDEEP<br /><em>PATIL</em></h1><div className="role-line"><span>▸</span> {rolesList[roles]}</div><p className="hero-statement">I build scalable systems, real-time applications, and intelligent products that turn ideas into working technology.</p><div className="hero-actions"><button className="primary" onClick={() => scrollTo('projects')}>EXPLORE MY WORK <b>↗</b></button><button className="ghost" onClick={() => scrollTo('contact')}>LET'S CONNECT <b>↗</b></button></div><p className="hero-meta">PARUL UNIVERSITY / COMPUTER SCIENCE ENGINEERING / 2023—2027</p></div><div className="core-stage"><div className="core-hud"><span>SYSTEM STATUS ........ <b>ONLINE</b></span><span>ENGINEERING MODE .... <b>ACTIVE</b></span><span>API SERVICES ........ <b>READY</b></span><span>DATABASE ............ <b>CONNECTED</b></span><span>AI CORE ............. <b>INITIALIZED</b></span><span>BUILD STATUS ........ <b>SHIPPING</b></span></div><div className="system-core">{['GO','JAVA','PYTHON','JAVASCRIPT','TYPESCRIPT','REACT','NODE.JS','POSTGRESQL','REDIS','MONGODB','DOCKER','GRAPHQL','WEBSOCKET','AI','LLM'].map((label, index) => <span className={`core-node node-${index}`} key={label} onMouseEnter={() => setHoveredTech(label)} onMouseLeave={() => setHoveredTech(null)}>{label}</span>)}<div className="black-hole"><strong>KP</strong></div><div className="core-ring ring-a" /><div className="core-ring ring-b" /><div className="core-ring ring-c" />{Array.from({ length: 18 }, (_, index) => <i className={`particle p-${index}`} key={index} />)}</div>{hoveredTech && <div className="tech-reveal"><strong>{hoveredTech}</strong><span>{['AI','LLM','CNN'].includes(hoveredTech) ? 'Intelligence Layer' : 'Engineering Stack'}</span><small>HOVER NODE / ORBIT LOCKED</small></div>}<div className="core-caption">ENGINEERING CORE <span>GRAVITY / v.2.0.26</span></div></div></div><div className="hero-footer"><span>01 / 08</span><span>SCROLL TO ENTER THE LAB ↓</span><span>VADODARA, INDIA</span></div></section>
  <section className="signal-strip"><div className="shell signal-grid">{[['680+','DSA PROBLEMS SOLVED'],['1744','LEETCODE RATING'],['1467','CODECHEF RATING'],['4+','APPLICATIONS / INTERNSHIP'],['90%','LATENCY IMPROVEMENT'],['30%','API RESPONSE IMPROVEMENT']].map(([number, label]) => <div className="signal" key={label}><strong>{number}</strong><small>{label}</small></div>)}</div></section>
  <section className="about shell section" id="about"><div className="section-kicker">02 / ENGINEER PROFILE</div><div className="about-layout"><div className="identity-card tilt-card"><div className="card-glow" /><span className="card-code">ID / KRP-2026</span><div className="card-avatar"><img src={heroImg} alt="Kuldeep Ravindra Patil" /></div><h2>KULDEEP<br /><em>PATIL</em></h2><p>SOFTWARE ENGINEER</p><div className="card-data"><span>STATUS ........ <b>ONLINE</b></span><span>MODE .......... <b>BUILDING</b></span><span>CREATIVITY .... <b>100%</b></span><span>CURIOSITY ..... <b>∞</b></span><span>SYSTEM ........ <b>ACTIVE</b></span></div><div className="card-footer">PARUL UNIVERSITY <span>◆</span> INDIA</div></div><div className="about-copy"><p className="eyebrow"><span>WHO IS KULDEEP?</span></p><h2>Engineer behind<br /><em>the systems.</em></h2><p>Software Engineer and Full Stack Developer focused on backend engineering, scalable APIs, real-time systems, distributed systems, AI-powered applications, and practical technology solutions.</p><p>My foundation spans Data Structures & Algorithms, software engineering, system design, APIs, databases, concurrency, and performance optimization. I like understanding how things work, then building a useful version of them.</p><div className="about-tags"><span>LEARN</span><span>BUILD</span><span>DEBUG</span><span>SHIP</span></div></div></div></section>
  <section className="experience shell section" id="experience"><div className="section-kicker">03 / PRODUCTION HISTORY</div><div className="section-title"><h2>Professional<br /><em>experience.</em></h2><p>One internship. Four-plus applications.<br />A lot of real-time systems.</p></div><div className="experience-panel"><div className="exp-top"><span className="exp-index">01</span><div><h3>CODTECH IT SOLUTIONS PVT. LTD.</h3><p>FULL STACK DEVELOPER INTERN / REMOTE</p></div><b>AUG 2025 — OCT 2025</b></div><div className="exp-body"><div className="production-screen"><div className="screen-top"><span>PRODUCTION / MERN_CLUSTER</span><i>● LIVE</i></div><div className="screen-bars"><span style={{ height: '72%' }} /><span style={{ height: '44%' }} /><span style={{ height: '88%' }} /><span style={{ height: '58%' }} /><span style={{ height: '96%' }} /><span style={{ height: '65%' }} /><span style={{ height: '82%' }} /><span style={{ height: '52%' }} /></div><div className="screen-footer">SOCKET.IO <b>90% FASTER</b> / MONGOOSE <b>30% OPTIMIZED</b></div></div><ul className="exp-list"><li>Developed and deployed 4+ web applications across collaboration, analytics, real-time communication, and productivity.</li><li>Built RESTful APIs, authentication workflows, reusable interfaces, middleware, validation, and error handling.</li><li>Implemented Socket.IO and WebSocket synchronization, reducing communication latency by 90%.</li><li>Optimized backend queries and redesigned Mongoose schemas, reducing API response time by 30%.</li><li>Collaborated through Git/GitHub, Agile SCRUM, debugging, code reviews, and deployment workflows.</li></ul></div></div></section>
  <section className="projects shell section" id="projects"><div className="section-kicker">04 / SYSTEMS PORTFOLIO</div><div className="section-title"><h2>Systems I’ve<br /><em>built.</em></h2><p>Ideas → Code → Systems → Products<br />Select a system to inspect the architecture.</p></div><div className="project-grid">{projects.map((project) => <article className="project-card" key={project.id} onClick={() => setSelected(project)}><div className="project-top"><span>PROJECT / {project.id}</span><span className="project-arrow">↗</span></div><div className={`project-visual visual-${project.id}`}><div className="visual-lines" /><strong>{project.title === 'FlowGuard' ? 'GATEWAY' : project.title === 'GoPulse' ? 'METRICS' : project.title === 'InterviewMind' ? 'LLM' : project.title === 'KrishiLens' ? 'CNN' : project.title === 'ChitChat' ? 'LIVE' : project.title === 'Productivity Tracker' ? 'FOCUS' : 'SYNC'}</strong><small>{project.id} / ACTIVE SYSTEM</small></div><p className="project-kind">{project.kind}</p><h3>{project.title}</h3><p className="project-summary">{project.summary}</p><div className="project-tags">{project.stack.slice(0, 4).map((tag) => <span key={tag}>{tag}</span>)}</div><button className="inspect">INSPECT SYSTEM <span>→</span></button></article>)}</div></section>
  <section className="systems shell section" id="systems"><div className="section-kicker">05 / SYSTEM ARCHITECTURE</div><div className="section-title"><h2>How I think<br /><em>about systems.</em></h2><p>Every layer has a job.<br />Every connection has a cost.</p></div><div className="architecture"><div className="arch-path">{[['CLIENT','React · React Native'],['API','REST · GraphQL · WebSockets'],['BACKEND','Go · Gin · Node · Express · FastAPI'],['DATA','PostgreSQL · MongoDB · Redis · Firebase'],['INFRASTRUCTURE','Docker · Git · GitHub']].map(([name, detail], index) => <div className="arch-layer" key={name}><span>0{index + 1}</span><div><h3>{name}</h3><p>{detail}</p></div>{index < 4 && <b>↓</b>}</div>)}</div><div className="data-stream"><span>REQUEST / 200</span><span>AUTH / VERIFIED</span><span>QUERY / CACHED</span><span>RESPONSE / 24ms</span></div></div></section>
  <section className="ai-lab shell section"><div className="section-kicker">06 / APPLIED INTELLIGENCE</div><div className="lab-layout"><div><h2>AI /<br /><em>intelligence lab.</em></h2><p>Applied AI experiments grounded in useful product workflows, from image analysis to adaptive technical interviews.</p><div className="lab-pills">{['LLM APIs','PROMPT ENGINEERING','EMBEDDINGS','CNN','AI APPLICATIONS','AUTOMATION'].map((pill) => <span key={pill}>{pill}</span>)}</div></div><div className="neural-lab"><div className="neural-core">AI</div>{Array.from({ length: 10 }, (_, index) => <span className={`neural-node nn-${index}`} key={index} />)}<div className="terminal"><div className="terminal-head"><span>● ● ●</span> KULDEEP_AI_CORE</div><p>&gt; boot</p><p>&gt; loading neural network...</p><p>&gt; connecting intelligence layer...</p><p className="cyan">&gt; system online</p><p>&gt; applied projects: InterviewMind / KrishiLens</p></div></div></div></section>
  <section className="skills shell section" id="skills"><div className="section-kicker">07 / TECHNOLOGY UNIVERSE</div><div className="section-title"><h2>My technical<br /><em>vocabulary.</em></h2><p>Tools are instruments.<br />Judgment is the real stack.</p></div><div className="tech-matrix">{techGroups.map(([group, ...items]) => <div className="tech-group" key={group}><h3>{group}</h3><div>{items.map((item, index) => <span className={index % 4 === 0 ? 'hot' : ''} key={item}>{item}</span>)}</div></div>)}</div></section>
  <section className="solve shell section" id="achievements"><div className="solve-copy"><div className="section-kicker">08 / PROBLEM SOLVING</div><h2>I don’t just build.<br /><em>I solve.</em></h2><p>Strong fundamentals make better systems. Kuldeep has solved more than 680 coding problems across programming platforms.</p><div className="ratings"><span>LEETCODE <b>1744</b></span><span>CODECHEF <b>1467</b></span></div></div><div className="algorithm"><div className="algo-label">ALGORITHM / GRAPH_TRAVERSAL</div>{Array.from({ length: 12 }, (_, index) => <i className={`algo-node an-${index}`} key={index}>{index === 0 ? 'S' : ''}</i>)}<div className="algo-line al-1" /><div className="algo-line al-2" /><div className="algo-line al-3" /><div className="algo-line al-4" /></div></section>
  <section className="certs shell section"><div className="section-kicker">09 / VERIFIED LEARNING</div><div className="cert-list">{['ServiceNow Certified System Administrator / CSA','ServiceNow Certified Application Developer / CAD','AWS Academy Cloud Foundations','Smart Interviews — Data Structures & Algorithms'].map((cert, index) => <div className="cert" key={cert}><span>0{index + 1}</span><p>{cert}</p><b>◆</b></div>)}</div></section>
  <section className="terminal-section shell section"><div className="section-kicker">10 / DEVELOPER CONSOLE</div><div className="terminal-large"><div className="terminal-head"><span>● ● ●</span> kuldeep@developer:~</div><div className="terminal-output">{terminalLines.map((line, index) => <p className={index % 2 ? 'muted' : ''} key={`${line}-${index}`}>{line}</p>)}</div><form onSubmit={runCommand}><span>&gt;</span><input value={terminalInput} onChange={(event) => setTerminalInput(event.target.value)} placeholder="type help to explore" aria-label="Developer terminal command" /></form></div></section>
  <section className="contact shell section" id="contact"><div className="contact-energy" /><div className="section-kicker">11 / OPEN CHANNEL</div><h2>Let’s build<br /><em>something real.</em></h2><p>Have an idea, technical challenge, or product worth building?</p><div className="contact-actions"><a className="primary" href="mailto:kp494563@gmail.com">START A CONVERSATION →</a><a className="ghost" href="https://github.com/kuldeeppatil2911" target="_blank" rel="noreferrer">GITHUB →</a><a className="ghost" href="https://www.linkedin.com/in/kuldeeppatil2911/" target="_blank" rel="noreferrer">LINKEDIN →</a></div><div className="contact-details"><a href="tel:+917875783726">+91 7875783726</a><a href="mailto:kp494563@gmail.com">kp494563@gmail.com</a><span>Vadodara, Gujarat / India</span></div></section>
  </main><footer className="footer shell"><strong>KULDEEP PATIL <span>◆</span></strong><span>Developer · AI Enthusiast · Builder</span><span>SYSTEM STATUS: ONLINE ●</span><span>© 2026</span></footer>
  {selected && <div className="case-study-backdrop" onClick={() => setSelected(null)}><article className="case-study" onClick={(event) => event.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button><p className="eyebrow"><span>PROJECT / {selected.id}</span> CASE STUDY</p><h2>{selected.title}<br /><em>{selected.kind}</em></h2><div className="case-tags">{selected.stack.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="case-grid"><div><small>PROBLEM</small><p>{selected.problem}</p></div><div><small>SOLUTION</small><p>{selected.solution}</p></div><div><small>RESULT</small><p>{selected.result}</p></div></div><div className="case-architecture"><span>CLIENTS</span><b>↓</b><span>API</span><b>↓</b><span>BACKEND</span><b>↓</b><span>DATABASE</span><b>↓</b><span>AI SERVICES</span></div><h3>KEY FEATURES</h3><ul>{selected.features.map((feature) => <li key={feature}>{feature}</li>)}</ul>{selected.url && <a className="primary case-link" href={selected.url} target="_blank" rel="noreferrer">OPEN LIVE PROJECT ↗</a>}</article></div>}
  </>
}

export default App
